In [0]:
# based on tutorial from 
# http://cs231n.github.io/python-numpy-tutorial/
# covers basic data structures and math operations

import numpy as np

In [0]:
# Initialize numpy arrays from nested Python lists, and access elements using square brackets

a=np.array([ [1,2,3],[7,8,9] ] ); print(a) # remember the use of another list [] around inside ones

[[1 2 3]
 [7 8 9]]


In [0]:
print(a.shape) # remember it still is an array of rank 2

(2, 3)


In [0]:
# To access the elements we will have to use square brackets
a[0,1]

2

In [0]:
# some already provided functions in np

b=np.zeros((2,3)); print(b) # see the double brackets

[[0. 0. 0.]
 [0. 0. 0.]]


In [0]:
c=a+b; print(c)

[[1. 2. 3.]
 [7. 8. 9.]]


In [0]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [0]:
print(a[1,0]); print(a)

5
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [0]:
b=a[:2,1:3]; print(b)

[[2 3]
 [6 7]]


In [0]:
# modifying b
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.-- very important

b[0,0]=99; print(a) # so my a also got modified with b

[[ 1 99  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
array1=np.array([list(range(3)),list(range(1,7,2))]); print(array1)

[[0 1 2]
 [1 3 5]]


In [0]:
array2=array1[:,1]; array3=array1[:,1:2] # accessing with low rank and high rank with slicing

In [6]:
print(array2,array2.shape); print(array3,array3.shape)

[1 3] (2,)
[[1]
 [3]] (2, 1)


In [9]:
# integer array indexing creates subarray [] while other
# one creates an array of higher rank
arr1=np.array([[1,2], [3, 4], [5, 6]]);
print(arr1[[0,1,2],[0,1,0]]) # equivalent to printing
print([arr1[0,0],arr1[1,1],arr1[2,0]])

[1 4 5]
[1, 4, 5]


In [11]:
print(arr1.dtype)

int64


In [13]:
arr1*arr1

array([[ 1,  4],
       [ 9, 16],
       [25, 36]])

In [15]:
arr1+arr1

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [20]:
print(arr1)
print(np.sum(arr1))# total sum, 
#sum rows giving column sum
print(np.sum(arr1,axis=0))
#sum columns giving rows sum
print(np.sum(arr1,axis=1))

[[1 2]
 [3 4]
 [5 6]]
21
[ 9 12]
[ 3  7 11]


In [22]:
arr1.T # transpose

array([[1, 3, 5],
       [2, 4, 6]])

In [40]:
# adding vector to matrix without using for loop

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

v=np.array([1,0,1]);
# tile up to make it same size as x
vv=np.tile(v,(len(x),1)); #print(vv)

# now we can add
NewY=x+vv; print(NewY)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [36]:
# gives number of rows
print(len(x))
# gives number of columns
print(len(x[0]))

4
3


In [42]:
# broadcasting
y=x+v; print(y) # row wise addition

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
